### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by Deeech** [mattbasta/crass#37]
Hello! I writing [tool](https://deeech.github.io/css-minificator-tests/) for minificators testing. It downloads several web sites, compresses them and does a screenshots to make sure that nothing been broken. And I found a minification bug of [this file](https://deeech.github.io/css-minificator-tests/site/github.com/css/github-b47d399ea95e9cb921b1706a8fac98426703f49c12f7e306ab52e8f52d4c887e.css).

```
`Parse error on line 1:
...kit-linear-gradient();background-image:l

-----------------------^
Expecting 'STRING', 'IDENT', 'S', '(', 'TO', '+', 'HEX_SHORT', 'HEX_LONG', 'FUNCTION_IDENT', '-', 'UNICODE_RANGE', 'IE_EXPRESSION', 'URL_FULL', 'CALC', 'ATTR', 'INTEGER', 'SCINOT', 'FLOAT', got ')'`
```

Is this minificator error or I just don't use it correctly?

**Comment by mattbasta** [comment]
Thanks for reaching out! I'll have a look at this later on tonight when I can sit down and dig in.

**Comment by mattbasta** [comment]
@Deeech it looks like the link to the CSS file is broken. Can you add a gist URL containing a copy of the CSS?

**Comment by Deeech** [comment]
[this works?](https://deeech.github.io/css-minificator-tests/site/github.com/css/github-b47d399ea95e9cb921b1706a8fac98426703f49c12f7e306ab52e8f52d4c887e.css)

https://gist.github.com/Deeech/a1534e5dbc60d5e98c0538b2230d4c7d

**Comment by mattbasta** [comment]
👌👌👌

**Comment by mattbasta** [comment]
I fat-fingered the commit message, but this should fix it: https://github.com/mattbasta/crass/commit/702dc5b1a5773d844ba2b75952b197faa5687ff6

If you test with version 0.7.12, that file should parse fine now.

The problem was `background-image: linear-gradient()` and the `-webkit-` prefixed variant. I'd never encountered an empty function before (it's technically invalid), and so the parsing failed. I've extended the grammar to support empty functions, which allows technically invalid CSS, but prevents failure. Using `--optimize` will also now remove declarations that use empty `linear-gradient`s.

**Comment by Deeech** [comment]
Great! I will update results of testing. Just interesting, what do you think about my tool? Could it be useful?

**Comment by mattbasta** [comment]
I think it's very useful! Historically, I've focused on http://goalsmashers.github.io/css-minification-benchmark/ as the sort of gold standard. That benchmark doesn't test correctness, though, and libraries like `more-css` consistently make unsafe transformations that result in what's effectively unusable output. I've worked very hard to only include default optimizations that I can show are either 100% provably correct, or hidden behind `-O1` that are almost always correct.

The tough part, as you've obviously seen [in results like these](https://deeech.github.io/css-minificator-tests/gemini-report/images/github.com/cssshrink/cssshrink/chrome~diff.png) is text rendering. Web font loading can cause all sorts of problems for doing diffs, because the load order doesn't necessarily correspond to lifecycle events like `window.onload` or `DOMContentLoaded`. It may be worthwhile to even disable web font loading, if possible.

You also potentially run into issues if you're using a weird implementation of WebKit (I haven't looked at what you're using, but I assume Phantom.js). Crass, for instance, will remove certain declarations that don't make sense (e.g., `-ms-foo: bar` inside `@-webkit-keyframes`, which can never apply) but certain browsers will alias those variants for compatibility purposes. The non-standard aliasing and potential differences from standards-based implementations can cause all sorts of minor bugs. Generally, though, those are few and far between, and I'd consider them bugs on the part of the browser. Phantom.js in particular, though, is known for being fairly out-of-date and having some weird edge cases in its rendering engine. Having worked with it before, I can say that you should be careful.

Otherwise, you're doing good work, and I appreciate you bringing this issue to my attention! Some things I'd like to see from `css-minificator-tests`:

- Comparison of file sizes (after minification, after gzip, and after minification+gzip)
- Percent difference from the reference screenshot, if there is a diff
- Time taken by each minification tool to run
- If the minification failed, what is the stderr output
- Ability to see results in a table, with sorting

Anyway, thanks again! Please let me know if you run into any other trouble.

**Comment by Deeech** [comment]
Thanks for the detailed response. Can you update crass npm package? https://www.npmjs.com/package/crass

**Comment by mattbasta** [comment]
My bad! Should be published now.
